### ISSUE TITLE
Geolocation component

### ISSUE THREAD

**Issue by JorgenJohansen** [IT2810/it2810-webutvikling-h18-prosjekt-3-47#16]
I videreføringen av en fungerende komponenet #13 der vi kan finne vår posisjon på et kart, har vi nå bestemt å lage en feature der bruker kan besøke forskjellige steder, få poeng for hver og at det kommer opp feedback om det er besøkt eller ikke.

**Comment by S1GGEN** [comment]
Litt |  Bilder
------------- | -------------
![image](https://user-images.githubusercontent.com/12127271/47214180-78835800-d39d-11e8-99e1-38970396cfe9.png)  | ![image](https://user-images.githubusercontent.com/12127271/47214214-90f37280-d39d-11e8-96e7-328a04fe095b.png)
![image](https://user-images.githubusercontent.com/12127271/47214166-66a1b500-d39d-11e8-8af8-c51fdc1e1a18.png)  | ![image](https://user-images.githubusercontent.com/12127271/47214275-af596e00-d39d-11e8-8010-bbfc7aa52781.png)
![image](https://user-images.githubusercontent.com/12127271/47214708-1deafb80-d39f-11e8-9503-8b03b65cea0e.png) | ![image](https://user-images.githubusercontent.com/12127271/47214716-20e5ec00-d39f-11e8-8512-a3a8b7b2658e.png)

**Comment by JorgenJohansen** [comment]
Lukkes med #18
