### ISSUE TITLE
Refaktorere/Renske opp i kode

### ISSUE THREAD

**Issue by S1GGEN** [IT2810/it2810-webutvikling-h18-prosjekt-3-47#19]
Det finnes en del inkonsistent kode i prosjektet, kan være fint å få rydda litt opp og gjort ting litt likere. 

Lurt å lese gjennom koden med kam, da klarer man som regel å snuble over noen småfeil.

~Bør også gjøre styles litt likere på tvers av komponentene, i dag er dette litt hulter i bulter~ Dette ble fikset som issue #25

**Comment by S1GGEN** [comment]
`Calendar` sender en warning hver gang den ikke får noe fra AsyncStorage. Dette er ikke nødvendig, og appen vil jo alltid få null fra AsyncStorage hvis den aldri har skrevet noe dit før. Så denne bør fjernes.

**Comment by S1GGEN** [comment]
Kan være kjekt å fjerne eksempelskjermene.
![image](https://user-images.githubusercontent.com/12127271/47203130-917d1080-d37f-11e8-9f75-fd9e17ceb421.png)

**Comment by S1GGEN** [comment]
Sjekke etter manglende semikolon og lignende

**Comment by JorgenJohansen** [comment]
Lukkes av #36
