### ISSUE TITLE
HOTFIX: Todolist

### ISSUE THREAD

**Issue by S1GGEN** [IT2810/it2810-webutvikling-h18-prosjekt-3-47#27]
TodoList sin delete benytter seg direkte av [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice), som er veldig liberal med hva slags input den aksepterer. 
![image](https://user-images.githubusercontent.com/12127271/47216718-327ec200-d3a6-11e8-8690-b7f9d4256235.png)
Det virker som om den evaluerer `start` til 0 hvis den ikke skjønner innholdet.

Vi bør nok derfor legge inn litt sjekker for å unngå eventuelle rare feil

```js
deleteTask = i => {
    this.setState(
      prevState => {
        let tasks = prevState.tasks.slice();

        tasks.splice(i, 1);

        return { tasks: tasks };
      },
      () => Tasks.save(this.state.tasks)
    );
  };
```

**Comment by JorgenJohansen** [comment]
Lukket av #29
