### ISSUE TITLE
Brainstorming om ekstrafunksjonalitet

### ISSUE THREAD

**Issue by S1GGEN** [IT2810/it2810-webutvikling-h18-prosjekt-3-47#4]
"Appen skal vise ett eksempel på noe som er utover basic React Native UI-problematikk (som bruk av gps, skritt-teller, direkte kommunikasjon med andre enheter - eller hva som helst annet relevant dere ønsker å utforske og som er innenfor begrensingene å få til)."

Her er det mange muligheter, vi har ganske frie tøyler. Viktig å passe på at dette vil fungere på både Android og iOS. Kjekt å bruke tredjepartskomponenter for mye av grunnfunksjonaliteten her, ikke vits å finne opp hjulet på nytt.

**Comment by oystholl** [comment]
Vi kan bruke kamera for å legge til bilder i notater og/eller kontakter. Lenke til kamera-komponent: https://github.com/react-native-community/react-native-camera

**Comment by S1GGEN** [comment]
Her er en skritteller-komponent vi kanskje kan  bruke til noe gøy:
[react-native-pedometer](https://github.com/victorpluna/react-native-pedometer)

**Comment by S1GGEN** [comment]
React Native har [geolocation](https://facebook.github.io/react-native/docs/geolocation), dette kan kanskje brukes. F.eks. kan brukeren sette seg et mål om å gå til en fjelltopp hver uke, da kan geolokasjon brukes til å tracke om dette målet oppnås.
[Medium-post om geolokasjon i React Native](https://medium.com/quick-code/react-native-location-tracking-14ab2c9e2db8)

**Comment by S1GGEN** [comment]
Lukket da vi bestemte oss for å implementere geolocation (se #16)
