### ISSUE TITLE
Sette opp Jest

### ISSUE THREAD

**Issue by S1GGEN** [IT2810/it2810-webutvikling-h18-prosjekt-3-47#5]
"Det skal utvikles tester med [Jest](https://jestjs.io/) og [Enzyme](https://github.com/airbnb/enzyme) og prosjektet skal vise god og systematisk testing av React applikasjoner."

Vi må sette opp Jest-runner og Enzyme, og skjønne hvordan disse må konfigureres for å funke sammen. Blogginnlegg som kanskje kan være til hjelp:

[Testing React with Jest and Enzyme (Medium.com)](https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675)

[Testing React Components with Enzyme and Jest (Scotch.io)](https://scotch.io/tutorials/testing-react-components-with-enzyme-and-jest)

[Testing React components with Jest and Enzyme (Hackernoon.com)](https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f)

**Comment by JorgenJohansen** [comment]
Vi har bare Jest i denne omgang, enzyme kommer i neste prosjekt :)

**Comment by JorgenJohansen** [comment]
Med tanke på at Jest er konfigurert i prosjektet og satt opp i develop med eksempeltester, kan denne issuen lukkes.
